#!/bin/sh

ldconfig

# Replace libGL.so.1 to libGLESv2.so.2 for libmutter
patchelf --replace-needed libGL.so.1 libGLESv2.so.2 /lib/aarch64-linux-gnu/libmutter-10.so.0.0.0

# Update xwayland from imx build
cp -f /bin/Xwayland_imx /bin/Xwayland

# Update cheese from imx build
cp -f /bin/cheese_imx /bin/cheese