HOMEPAGE = "http://www.ubuntu.org"
# This LICENSE entry really needs to be fixed. Desktop passes through
# open source software and we have an aggregated set of open source
# licenses that is hard to characterize. If anyone can suggest a proper
# way to fix this, please do so! The MIT related entry is borrowed
# from the merge-files recipe to show intent of passing through
# files from other origins in a proper fashion.
# <Heinz.Wrobel@nxp.com>
#LICENSE = "Desktop"
#LIC_FILES_CHKSUM = "file://ubuntu-base-16.04-core-arm64.tar.gz;md5=083ddc08f15fd0fc0c0a3fd10f33bd9b"
LICENSE = "MIT"
LIC_FILES_CHKSUM = "file://${COMMON_LICENSE_DIR}/GPL-2.0;md5=801f80980d171dd6425610833a22dbe6 \
                    file://${COMMON_LICENSE_DIR}/MIT;md5=0835ade698e0bcf8506ecda2f7b4f302"
